### ISSUE TITLE
初次进入https://share121.github.io/inter_knot/会报错

### ISSUE THREAD

**Issue by Pleasurecruise** [share121/inter-knot#3792]
### Type

安全问题

### Bug 描述

Error: https://api.github.com/graphql

Response:
{message: Bad credentials, documentation_url: https://docs.github.com/graphql, status: 401}

Error Object:
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Stack Trace:
Error
    at Object.n6 (https://share121.github.io/inter_knot/main.dart.js:7575:18)
    at https://share121.github.io/inter_knot/main.dart.js:62806:5
    at bbO.a (https://share121.github.io/inter_knot/main.dart.js:6032:63)
    at bbO.$2 (https://share121.github.io/inter_knot/main.dart.js:53399:14)
    at Object.t (https://share121.github.io/inter_knot/main.dart.js:6018:10)
    at awO.aYw (https://share121.github.io/inter_knot/main.dart.js:62863:10)
    at awO.F0 (https://share121.github.io/inter_knot/main.dart.js:62799:35)
    at awO.aYu (https://share121.github.io/inter_knot/main.dart.js:62800:30)
    at https://share121.github.io/inter_knot/main.dart.js:33398:20
    at bbO.a (https://share121.github.io/inter_knot/main.dart.js:6032:63)

### 截屏或视频

![屏幕截图 2024-08-28 192804](https://github.com/user-attachments/assets/24bd9461-75b6-48e3-8bca-742cccd6c523)

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by Pleasurecruise** [comment]
> 感谢你提供的错误代码。 不过这个是没有问题的，你可以无视他。 这个是因为不必要的代码产生的，不会对于新绳网带来其他的影响，可以正常使用。

主要一定程度上影响使用体验
